"""
ks-eye Multi-Format Export Engine
Markdown, CSV, Email Newsletter, README, Notion/Obsidian exports
All text-based for terminal use
"""

import csv
import io
import json
import os
import re
from datetime import datetime
from ks_eye.config import config
from ks_eye.ui import console


def export_to_markdown(content, title="Research Report", metadata=None):
    """Convert research content to well-formatted Markdown"""
    lines = []
    
    # Front matter
    lines.append("---")
    lines.append(f"title: '{title}'")
    lines.append(f"date: {datetime.now().strftime('%Y-%m-%d')}")
    if metadata:
        for key, value in metadata.items():
            lines.append(f"{key}: '{value}'")
    lines.append("---")
    lines.append("")
    
    # Title
    lines.append(f"# {title}")
    lines.append("")
    
    # Convert content - look for headings and format them
    paragraphs = content.split("\n")
    in_list = False
    
    for line in paragraphs:
        line = line.strip()
        if not line:
            if in_list:
                in_list = False
            lines.append("")
            continue
        
        # Check for ALL CAPS headings
        if line.isupper() and len(line) < 80 and len(line) > 3:
            lines.append(f"## {line.title()}")
            lines.append("")
        # Check for numbered sections
        elif re.match(r'^\d+[\.\)]\s+[A-Z]', line):
            lines.append(f"## {line}")
            lines.append("")
        # Check for bullet points
        elif line.startswith("-") or line.startswith("•"):
            if not in_list:
                lines.append("")
                in_list = True
            lines.append(f"  {line}")
        # Regular paragraph
        else:
            if in_list:
                lines.append("")
                in_list = False
            # Bold text in ALL CAPS within sentences
            line = re.sub(r'\*\*([^*]+)\*\*', r'**\1**', line)
            lines.append(line)
            lines.append("")
    
    # Footer
    lines.append("")
    lines.append("---")
    lines.append(f"*Generated by ks-eye Research Assistant on {datetime.now().strftime('%Y-%m-%d %H:%M')}*")
    
    return "\n".join(lines)


def export_to_csv(data_points, filename=None):
    """Export data points to CSV format"""
    if not data_points:
        return None, "No data to export"
    
    output = io.StringIO()
    
    # Determine columns from first data point
    if isinstance(data_points[0], dict):
        fieldnames = list(data_points[0].keys())
        writer = csv.DictWriter(output, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(data_points)
    else:
        writer = csv.writer(output)
        for row in data_points:
            writer.writerow(row if isinstance(row, (list, tuple)) else [row])
    
    csv_content = output.getvalue()
    
    if not filename:
        ts = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = os.path.join(config.RESEARCH_DIR, f"data_export_{ts}.csv")
    
    os.makedirs(os.path.dirname(filename), exist_ok=True)
    with open(filename, "w") as f:
        f.write(csv_content)
    
    return filename, csv_content


def generate_email_newsletter(content, title="Research Update", max_length=2000):
    """Generate an email newsletter format from research"""
    lines = []
    
    # Email header
    lines.append(f"Subject: {title}")
    lines.append(f"From: research@kseye.ai")
    lines.append(f"Date: {datetime.now().strftime('%B %d, %Y')}")
    lines.append("")
    lines.append("=" * 60)
    lines.append("")
    
    # Preheader
    lines.append(f"[PREVIEW] Key findings from our latest research on {title}")
    lines.append("")
    
    # Body
    lines.append("Hi there,")
    lines.append("")
    lines.append(f"We've completed new research on **{title}**. Here are the key findings:")
    lines.append("")
    
    # Extract key points
    sentences = content.replace("\n", " ").split(".")
    key_points = [s.strip() for s in sentences[:8] if len(s.strip()) > 50]
    
    for i, point in enumerate(key_points[:5], 1):
        lines.append(f"{i}. {point}.")
        lines.append("")
    
    # Read more section
    lines.append("")
    lines.append("=" * 60)
    lines.append("READ THE FULL REPORT")
    lines.append("=" * 60)
    lines.append("")
    
    # Include excerpt
    excerpt = content[:max_length]
    lines.append(excerpt)
    
    if len(content) > max_length:
        lines.append("")
        lines.append("[... Read full report for complete analysis ...]")
    
    # Footer
    lines.append("")
    lines.append("=" * 60)
    lines.append("Generated by ks-eye Research Assistant")
    lines.append(f"Date: {datetime.now().strftime('%Y-%m-%d')}")
    lines.append("=" * 60)
    
    return "\n".join(lines)


def generate_readme(topic, content, folder_path=""):
    """Generate README.md for GitHub repo"""
    lines = []
    
    lines.append(f"# {topic}")
    lines.append("")
    lines.append(f"Research report generated by [ks-eye](https://github.com/ks-eye)")
    lines.append("")
    
    # Table of contents
    lines.append("## Table of Contents")
    lines.append("")
    lines.append("- [Overview](#overview)")
    lines.append("- [Key Findings](#key-findings)")
    lines.append("- [Analysis](#analysis)")
    lines.append("- [Sources](#sources)")
    lines.append("- [Usage](#usage)")
    lines.append("")
    
    # Overview
    lines.append("## Overview")
    lines.append("")
    lines.append(f"This repository contains research findings on **{topic}**.")
    lines.append("")
    lines.append(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    lines.append("")
    
    # Key Findings
    lines.append("## Key Findings")
    lines.append("")
    
    # Extract key sentences
    sentences = content.replace("\n", " ").split(".")
    key_findings = [s.strip() for s in sentences[:6] if len(s.strip()) > 80]
    
    for finding in key_findings[:5]:
        lines.append(f"- {finding}.")
    
    lines.append("")
    
    # Analysis
    lines.append("## Analysis")
    lines.append("")
    lines.append("```")
    lines.append(content[:2000])
    lines.append("```")
    lines.append("")
    
    # Sources
    lines.append("## Sources")
    lines.append("")
    lines.append("See `sources_and_links.txt` for complete source list.")
    lines.append("")
    
    # Usage
    lines.append("## Usage")
    lines.append("")
    lines.append("```bash")
    lines.append("# Install ks-eye")
    lines.append("pip install ks-eye")
    lines.append("")
    lines.append("# Reproduce this research")
    lines.append(f"kseye quick -t \"{topic}\"")
    lines.append("```")
    lines.append("")
    
    # License
    lines.append("---")
    lines.append(f"*Generated by ks-eye Research Assistant*")
    
    return "\n".join(lines)


def export_to_notion_obsidian(content, title="Research", format_type="notion"):
    """
    Export to Notion or Obsidian format
    Both use markdown but with different conventions
    """
    lines = []
    
    if format_type == "notion":
        # Notion-style markdown
        lines.append(f"# {title}")
        lines.append("")
        
        # Notion callouts
        lines.append(f"> 💡 Research on {title}")
        lines.append(f"> Generated: {datetime.now().strftime('%Y-%m-%d')}")
        lines.append("")
        
        # Convert content
        paragraphs = content.split("\n\n")
        for para in paragraphs[:20]:
            if para.strip().isupper() and len(para.strip()) < 80:
                lines.append(f"## {para.strip().title()}")
                lines.append("")
            else:
                lines.append(para.strip())
                lines.append("")
    
    elif format_type == "obsidian":
        # Obsidian-style markdown with wikilinks
        lines.append(f"# {title}")
        lines.append("")
        
        # Tags
        lines.append("Tags: #research #analysis #ks-eye")
        lines.append(f"Date: {datetime.now().strftime('%Y-%m-%d')}")
        lines.append("")
        
        # Convert content with wikilinks for key concepts
        import re
        concept_pattern = re.compile(r'\b[A-Z][a-z]+(?:\s+[A-Z][a-z]+)*\b')
        
        paragraphs = content.split("\n\n")
        for para in paragraphs[:20]:
            # Add wikilinks to concepts
            para_with_links = para
            for match in concept_pattern.finditer(para):
                concept = match.group()
                if len(concept) > 4:
                    para_with_links = para_with_links.replace(concept, f"[[{concept}]]", 1)
            
            if para.strip().isupper() and len(para.strip()) < 80:
                lines.append(f"## {para.strip().title()}")
                lines.append("")
            else:
                lines.append(para_with_links.strip())
                lines.append("")
    
    return "\n".join(lines)


def save_export(content, export_type, topic, folder=None):
    """Save export to file and return path"""
    if not folder:
        ts = datetime.now().strftime("%Y%m%d_%H%M%S")
        safe_topic = "".join(c if c.isalnum() else "_" for c in topic)[:40]
        folder = os.path.join(config.RESEARCH_DIR, f"exports_{safe_topic}_{ts}")
    
    os.makedirs(folder, exist_ok=True)
    
    if export_type == "markdown":
        filename = os.path.join(folder, f"{topic[:30].replace(' ', '_')}.md")
    elif export_type == "csv":
        filename = os.path.join(folder, f"{topic[:30].replace(' ', '_')}.csv")
    elif export_type == "newsletter":
        filename = os.path.join(folder, f"newsletter_{topic[:30].replace(' ', '_')}.txt")
    elif export_type == "readme":
        filename = os.path.join(folder, "README.md")
    elif export_type == "notion":
        filename = os.path.join(folder, f"{topic[:30].replace(' ', '_')}_notion.md")
    elif export_type == "obsidian":
        filename = os.path.join(folder, f"{topic[:30].replace(' ', '_')}_obsidian.md")
    else:
        filename = os.path.join(folder, f"export_{topic[:30].replace(' ', '_')}.txt")
    
    with open(filename, "w") as f:
        f.write(content)
    
    return filename, folder


def generate_all_exports(content, topic, folder=None):
    """Generate all export formats and return paths"""
    exports = {}
    
    # Markdown
    md_content = export_to_markdown(content, topic)
    md_path, folder = save_export(md_content, "markdown", topic, folder)
    exports["markdown"] = md_path
    
    # Email Newsletter
    newsletter_content = generate_email_newsletter(content, topic)
    nl_path, folder = save_export(newsletter_content, "newsletter", topic, folder)
    exports["newsletter"] = nl_path
    
    # README
    readme_content = generate_readme(topic, content, folder)
    readme_path, folder = save_export(readme_content, "readme", topic, folder)
    exports["readme"] = readme_path
    
    # Notion
    notion_content = export_to_notion_obsidian(content, topic, "notion")
    notion_path, folder = save_export(notion_content, "notion", topic, folder)
    exports["notion"] = notion_path
    
    # Obsidian
    obsidian_content = export_to_notion_obsidian(content, topic, "obsidian")
    obsidian_path, folder = save_export(obsidian_content, "obsidian", topic, folder)
    exports["obsidian"] = obsidian_path
    
    return exports, folder
